services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:9000"
    environment:
      - DB_CONNECTION=mongodb
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_DATABASE=ticketing
      - DB_USERNAME=rocket9
      - DB_PASSWORD=rocket9
    depends_on:
      mongodb:
        condition: service_healthy
    command: >
      sh -c "php artisan migrate && php artisan db:seed && php artisan jwt:secret && php-fpm"

  mongodb:
    image: mongo:5.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: rocket9
      MONGO_INITDB_ROOT_PASSWORD: rocket9
      MONGO_INITDB_DATABASE: ticketing
    volumes:
      - mongodb_data:/data/db

    healthcheck: 
      test: echo 'db.runCommand({find:"app_db_name.devUser"}).ok' | mongosh --authenticationDatabase admin --host localhost -u rocket9 -p rocket9 admin --quiet | grep -q 1
      interval: 10s
      timeout: 60s
      retries: 3
      start_period: 20s

    # healthcheck:
    #   test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongodb_data:
